"""Creating all tables

Revision ID: 86c8ba3f22c4
Revises: 
Create Date: 2024-05-28 09:25:45.037898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c8ba3f22c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.Enum('Geral', 'Selecionados', 'Publico'), nullable=False),
    sa.Column('access_users_ids', sa.Integer(), nullable=True),
    sa.Column('uploader_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_users_ids'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['Files.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permissions')
    # ### end Alembic commands ###
